### ISSUE TITLE
texture

### ISSUE THREAD

**Issue by mosabTALJO** [felipebaltazar/Xamarin.Forms.AR#1]
hello, I'm like what you have made but it seems the textures are not loading properly, were you able to come up with a solution for that? Thank you.

**Comment by felipebaltazar** [comment]
Hello @mosabTALJO!
It seems like a problem with BlendMode, commenting the `renderer.SetBlendMode(BlendMode.AlphaBlending);` line all textures work fine.

I've opened this PR to solve this
https://github.com/felipebaltazar/Xamarin.Forms.AR/pull/2

![image](https://user-images.githubusercontent.com/19656249/187051814-b582bf47-75b4-400a-b061-831916204dfb.png)

**Comment by mosabTALJO** [comment]
Awesome work @felipebaltazar, and thank you for responding.
